# -*- coding: utf-8 -*-
"""Cartpole.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11OZt7Ha5i0kx6DXaNAPS_pS4QlXm6_S9
"""

import gym

# create and initialize the environment
env = gym.make("CartPole-v1")
env.reset()

# play 10 games
for i in range(10):
    # initialize the variables
    done = False
    game_rew = 0

    while not done:
      # choose a random action
      action = env.action_space.sample()
      # take a step in the environment
      new_obs, rew, done, info = env.step(action)
      game_rew += rew
      # when is done, print the cumulative reward of the game and reset the environment
      if done:
        print('Episode %d finished, reward:%d' % (i, game_rew))
        env.reset()